name: CI Pipeline

permissions:
  contents: write
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate:
    name: Lint, Test & Security Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pip-audit

      - name: Run lint
        run: |
          flake8 app.py

      - name: Run unit tests
        run: |
          pytest

      - name: Dependency vulnerability scan
        run: |
          pip install pip-audit
          pip-audit

      - name: Secret scan
        uses: gitleaks/gitleaks-action@v2

      - name: Repository hygiene check
        run: python scripts/repo_hygiene.py

      - name: Generate PR Summary
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/ai_pr_summary.py

      - name: Commit PR Summary
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add docs/PR_SUMMARY.md

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
           git commit -m "Auto-update PR summary [skip ci]"
           git push
          fi

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devex-app:latest .
